# Generated by Django 5.2.17 on 2026-08-14 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_artistprofile_clientprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='profile_pics/'),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='profile_pics/'),
        ),
    ]
