# Generated by Django 5.2.17 on 2026-08-11 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Photographer, Painter, Musician', max_length=50, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional description of this category')),
            ],
            options={
                'verbose_name': 'Artist Type',
                'verbose_name_plural': 'Artist Types',
                'ordering': ['name'],
            },
        ),
    ]
