# Generated by Django 5.2.17 on 2026-08-11 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0002_post_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='media',
            field=models.FileField(help_text='Upload image, video (MP4/WebM), audio (MP3/WAV), or PDF document', upload_to='portfolio_posts/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Optional artwork/service price in ₹', max_digits=10, null=True),
        ),
    ]
