# Generated by Django 5.2.17 on 2026-08-11 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0003_alter_post_media_alter_post_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Optional cover/thumbnail image for video, audio, or PDF document', null=True, upload_to='portfolio_thumbnails/'),
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
