# Generated by Django 5.2.17 on 2026-08-14 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0005_seed_artist_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='media',
            field=models.FileField(help_text='Upload image, video (MP4/WebM), audio (MP3/WAV), or PDF document', max_length=500, upload_to='portfolio_posts/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Optional cover/thumbnail image for video, audio, or PDF document', max_length=500, null=True, upload_to='portfolio_thumbnails/'),
        ),
    ]
